# Generated by Django 3.1.7 on 2021-03-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('userID', models.CharField(max_length=30)),
                ('userPW', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
